name: ar-flask-app-workflow-final
on: push
jobs:
    flask-ci-job:
        runs-on: ubuntu-latest

        steps:
            - name: checkout Repository
              uses: actions/checkout@v7
            
            - name: docker build image
              run:  docker build -t ar-flask-app:v1.0.0 .
            
            - name: docker run container
              run: docker container run -d -p 5000:5000 --name ar-flask-app ar-flask-app:v1.0.0
            
            - name: smoke test
              run: |
                sleep 5
                curl http://localhost:5000/health
            